---
- hosts: all
  tasks:

    - name: Create Network
      community.docker.docker_network:
        name: wordpress
      
    - name: Deploy Wordpress
      community.docker.docker_container:
        name: Wordpress
        image: wordpress:latest
        ports:
          - "80:80"
        networks:
          - name: wordpress
        volumes:
          - wordpress:/var/www/html
        env:
          WORDPRESS_DB_HOST: "db"
          WORDPRESS_DB_USER: "user"
          WORDPRESS_DB_PASSWORD: "pass"
          WORDPRESS_DB_NAME: "db"
        restart_policy: always

    - name: Deploy MYSQL
      community.docker.docker_container:
        name: db
        image: mysql:5.7
        networks:
          - name: wordpress
        volumes: 
          - db:/var/lib/mysql
        env:
          MYSQL_DATABASE: "db"
          MYSQL_USER: "user"
          MYSQL_PASSWORD: "pass"
          MYSQL_RANDOM_ROOT_PASSWORD: "1"

        restart_policy: always
